config/routes.rb
Rails.application.routes.draw do

  # Home page
  root                'static_pages#home'
  
  # Static pages
  get 'resume'     => 'static_pages#resume'
  get 'contact'    => 'static_pages#contact'
  
  # Session
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  
  # Blog
  resources :articles
end

app/models/article.rb
class Article < ActiveRecord::Base
    default_scope -> { order(created_at: :desc) }
    validates :title, presence: true, length: { maximum: 140, :message => 'Title has a maximum length of 140 characters.' }
    validates :text, presence: true, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  force_ssl if: :ssl_configured_for_user?
  
  include SessionsHelper
  
  private
        # Confirms a logged-in user.
        def logged_in_user
          unless logged_in?
            store_location
            flash[:danger] = "Please log in."
            redirect_to login_url
          end
        end
        
        def ssl_configured_for_user?
          !Rails.env.development? && logged_in?
        end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :logged_in_user, only: [:new, :create, :destroy, :edit, :update]
    
    def new
        @article = Article.new
    end
    
    def edit
        @article = Article.find(params[:id])
    end
    
    def index
        @articles = Article.all
    end
    
    def show
        @article = Article.find(params[:id])
    end
    
    def create
        @article = Article.new(article_params)
        
        @article.save
        redirect_to @article
    end
    
    def update
        @article = Article.find(params[:id])
        
        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
        end
    end
    
    def destroy
        @article = Article.find(params[:id])
        
        @article.destroy
        flash[:success] = "Article deleted"
        redirect_to articles_path
    end
    
    private
        def article_params
            params.require(:article).permit(:title, :text)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  force_ssl if: :ssl_configured?, only: [:new, :create]
  
  def new
  end
  
  def create
    if authenticate? params[:session][:password]
      log_in
      flash[:success] = "Logged in successfully!"
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid password'
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
  private 
    def ssl_configured?
      !Rails.env.development?
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def resume
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    # Returns the full title on a per-page basis
    def full_title(page_title = '')
        base_title = "GabeCode"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
    
    # Helper class for CodeRay renderer
    class CodeRayify < Redcarpet::Render::HTML
      def block_code(code, language)
        CodeRay.scan(code, language).div
      end
    end
    
    # Generates HTML from markdown text
    def markdown(content)
        @markdown_renderer ||= CodeRayify.new(:filter_html => true, :hard_wrap => true)
                                
        @markdown_options ||= {
            :fenced_code_blocks => true,
            :no_intra_emphasis => true,
            :autolink => true,
            :lax_html_blocks => true,
        }
        
        @markdown ||= Redcarpet::Markdown.new(@markdown_renderer, @markdown_options)
        @markdown.render(content).html_safe
    end
    
    
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Returns true is the given password is correct
    def authenticate?(password)
        ENV['PASS_HASH'] == BCrypt::Engine.hash_secret(password, ENV['PASS_SALT'])
    end
    
    # Logs in the given user.
    def log_in
        session[:logged_in] = true
    end
    
    def log_out
        session.delete(:logged_in)
    end
    
    # Returns true if the user is logged in, false otherwise.
    def logged_in?
        session[:logged_in]
    end
    
    def redirect_back_or(default)
        redirect_to(session[:return_to] || default)
        session.delete(:return_to)
    end
    
    def store_location
        session[:return_to] = request.url
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_form.html.erb
<%= form_for :article, url: articles_path do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@article.errors.count, "error") %> prohibited
                this article from being saved:
            </h2>
            <ul>
                <% @article.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>

    <%= f.label :text %><br>
    <%= f.text_area :text, class: "form-control", rows: "3" %>

    <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/articles/edit.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Edit Article</h1>
  <%= render 'form' %>
  <%= link_to 'Delete', @article, method: :delete, data: { confirm: "You sure?" } %>
  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<% provide(:title, "Blog") %>

<div class="col-md-8 col-md-offset-2">
    
    <% if logged_in? %>
        <p><%= link_to "Write Post", new_article_path, class: "btn btn-primary btn-lg" %></p>
    <% end %>
    
    <% @articles.each do |article| %>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2><%= link_to article.title, article %></h2>
                <%= article.created_at.strftime("%B %-d, %Y") %>
            </div>
            <div class="panel-body">
                <%= sanitize(truncate(markdown(article.text), length: 250, escape: false)) %>
                <%= link_to 'Read More', article %>
            </div>
            <% if logged_in? %>
                <div class="panel-footer">
                    <%= link_to 'Delete', article, method: :delete,
                                                   data: { confirm: "You sure?" },
                                                   class: "btn btn-primary" %>
                    <%= link_to 'Edit', edit_article_path(article),
                                        class: "btn btn-primary" %>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

app/views/articles/new.html.erb
<% provide(:title, "Write Post") %>

<div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
    <div class="panel-heading">
        <h2>Write Post</h2>
    </div>
    
    <div class="panel-body">
        <%= render 'form' %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<% provide(:title, "Blog") %>

<div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2><%= link_to @article.title, @article %></h2> posted on <%= @article.created_at %>
        </div>
        
        <div class="panel-body">
            <%= markdown(@article.text) %>
        </div>
    
        <% if logged_in? %>
            <div class="panel-footer">
                <%= link_to 'Back', articles_path, class: "btn btn-primary" %>
                <%= link_to 'Delete', @article, method: :delete,
                                      data: { confirm: "You sure?" },
                                      class: "btn btn-primary" %>
                <%= link_to 'Edit', edit_article_path(@article),
                                    class: "btn btn-primary" %>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-inverse navbar-fixed-bottom">
    Copyright&#169; 2016 <a href="mailto:zettablade@gmail.com">Gabriel Anderson</a>
</div>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-fixed-top navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "GabeCode", root_path, class: "navbar-brand" %>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><%= link_to "Blog",    articles_path %></li>
                    <li><%= link_to "Resume",  resume_path %></li>
                    <li><%= link_to "Contact", contact_path %></li>
                    <% if logged_in? %>
                        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                    <% end %>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application',
                                'https://fonts.googleapis.com/css?family=Cookie',
                                'https://fonts.googleapis.com/css?family=Droid+Sans',
                                media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    
    
    <!-- <div class="col-md-8 col-md-offset-2"> -->
      <%= yield %>
    <!-- </div> -->
  
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>Contact Information</h2>
        </div>
        <div class="panel-body">
            <p>
                <i>Please do not use this information for evil.</i>
                <br><u>Email</u> - <a href="mailto:zettablade@gmail.com">zettablade@gmail.com</a>
                <br><u>Phone</u> - 206.546.1914
                <br><u>Github</u> - <a href="http://www.github.com/andgate" target="_blank">www.github.com/andgate</a>
            </p>
        </div>
    </div>
</div>

app/views/static_pages/home.html.erb
<div class="col-md-3 col-md-offset-1">

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>Gabriel Anderson</h2>
        </div>
        <div class="panel-body">
            <%= image_tag("profile.jpg", :alt => "Gabe and Pabu", :class => "img-thumbnail") %>
        </div>
    </div>
    
</div>

          
<div class="col-md-7">         
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>About Me</h2>
        </div>
        <div class="panel-body">
            <p>
                My name is Gabriel Anderson.
                <br>
                <br>I live in Richmond Beach, WA with my girlfrend Raleigh and our bird Pabu.
                <br>
                <br>I've been programming since I was 13-years-old.
                <br>My first platform was the Sony Playstation Portable.
                <br>My first programming language was C.
                <br>
                <br>I love managing large projects.
                <br>I love solving problems.
                <br>I love learning new technologies.
                <br>I love talking about software development.
                <br>
                <br>I am currently looking to enter the software industry. Please take a look at my <%= link_to "resume", resume_path %> if you are interested.
            </p>
        </div>
    </div>
</div>

app/views/static_pages/resume.html.erb
<% provide(:title, "Resume") %>
<div class="col-md-3 col-md-offset-1">
    <center>
        
    <h2>Gabriel Anderson</h2>
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>Resume</h2>
        </div>
        <div class="panel-body">
            <p>
                Hello, my name is Gabriel Anderson, and I am a programmer.
                <br>You can download this resume as a
                <%= link_to "pdf file", "/resume.pdf", target: "_blank" %>
                or a 
                <%= link_to "word document", "/resume.docx", target: "_blank" %>
                .
            </p>
        </div>
    </div>
        
    <h2>Skills</h2>
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>Languages</h2>
        </div>
        <div class="panel-body">
            Java • C++ • Haskell • Ruby
        </div>
    </div>
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>Technologies</h2>
        </div>
        <div class="panel-body">
            <h3>Libraries</h3>
            libgdx • sdl • rails
            
            <h3>Databases</h3>
            postgresql • sqlite
            
            <h3>Tools</h3>
            git • vim
            
            <h3>Operating Systems</h3>
            windows • android • linux
        </div>
    </div>
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2>Education</h2>
        </div>
        <div class="panel-body">
            <h3>Shoreline Community College</h3>
            Associate of Arts (A.A.), Computer Science, 3.68 GPA
            <br> March 2016 | Shoreline, WA
        </div>
    </div>
    
    <center>
</div>

<div class="col-md-7">
    
    <h2>Projects</h2>
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2><a href="http://github.com/andgate/pokeadot" target="_blank">Poke-A-Dot</a> | Game</h2>
        </div>
        <div class="panel-body">
            <ul>
                <li>Designed and built a dot-poking game challenging player reaction-time</li>
                <li>Developed with LibGDX in Java for Android and PC</li>
                <li>Marketed free and paid version on Google Play</li>
                <li>Implemented a polished user-interface</li>
            </ul>
        </div>
    </div>
    
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2><a href="http://www.github.com/andgate/ikou" target="_blank">Ikou</a> | Game</h2>
        </div>
        <div class="panel-body">
            <ul>
                <li>Challenges players to solve an endless barrage of mazes</li>
                <li>Developed with LibGDX in Java for Android and PC</li>
                <li>Marketed free and paid version on Google Play</li>
                <li>Implemented random maze generation using the Recursive Backtracer Algorithm</li>
                <li>Developed a custom maze mesh generator that works similar to a voxel engine</li>
                <li>Invented a minimalistic control scheme and user-interface</li>
                <li>Currently developing a second version in my spare time which will have a competitive online multiplayer experience</li>
            </ul>
        </div>
    </div>
    
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2><a href="http://www.github.com/andgate/gabecode" target="_blank">GabeCode</a> | Blogfolio</h2>
        </div>
        <div class="panel-body">
            <ul>
                <li>Developed a personal website and single-user</li>
                <li>Implemented with Ruby-On-Rails and deployed via Heroku</li>
                <li>Employed MarkDown formatting to render blog posts</li>
            </ul>
        </div>
    </div>
    
    
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2><a href="http://www.github.com/andgate/hawk" target="_blank">Hawk</a> | Programming Language</h2>
        </div>
        <div class="panel-body">
            <ul>
                <li>Designed and implemented an experimental, low-level, programming language</li>
                <li>Wrote two different proto-type compilers with C++ and Haskell respectively</li>
                <li>Developed an abstract syntax tree with C++</li>
                <li>Implemented parsing with Bison+Flex in C++</li>
                <li>Created a code generator that outputs to LLVM IR code using the LLVM C++ library</li>
                <li>Wrote a detailed guide to document usage of language</li>
                <li>Actively researching and developing features for the compiler such as type-inference, type-checking, and error reporting</li>
            </ul>
        </div>
    </div>
</div>